//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.239
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ideastrike.Nancy.Localization {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Ideastrike.Nancy.Localization.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to General Settings.
        /// </summary>
        public static string Admin_GeneralSettings {
            get {
                return ResourceManager.GetString("Admin_GeneralSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Google Analytics.
        /// </summary>
        public static string Admin_GoogleAnalytics {
            get {
                return ResourceManager.GetString("Admin_GoogleAnalytics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to It should look something like UA-XXXXXXX-X.
        /// </summary>
        public static string Admin_GoogleAnalyticsHelp {
            get {
                return ResourceManager.GetString("Admin_GoogleAnalyticsHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Admin Home.
        /// </summary>
        public static string Admin_Home {
            get {
                return ResourceManager.GetString("Admin_Home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home Page.
        /// </summary>
        public static string Admin_Homepage {
            get {
                return ResourceManager.GetString("Admin_Homepage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Link back to your website.
        /// </summary>
        public static string Admin_HomepageHelp {
            get {
                return ResourceManager.GetString("Admin_HomepageHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image Settings.
        /// </summary>
        public static string Admin_ImageSettings {
            get {
                return ResourceManager.GetString("Admin_ImageSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Moderation.
        /// </summary>
        public static string Admin_Moderation {
            get {
                return ResourceManager.GetString("Admin_Moderation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The name of the individual or organisation running.
        /// </summary>
        public static string Admin_OrganizationNameHelp {
            get {
                return ResourceManager.GetString("Admin_OrganizationNameHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This is what visitors will see at the root of your Ideastrike install..
        /// </summary>
        public static string Admin_RootHelp {
            get {
                return ResourceManager.GetString("Admin_RootHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string Admin_Settings {
            get {
                return ResourceManager.GetString("Admin_Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Site Title.
        /// </summary>
        public static string Admin_SiteTitle {
            get {
                return ResourceManager.GetString("Admin_SiteTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thumbnail Width.
        /// </summary>
        public static string Admin_ThumbnailWidth {
            get {
                return ResourceManager.GetString("Admin_ThumbnailWidth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The maximum width in pixels for image thumbnails (default is 1000).
        /// </summary>
        public static string Admin_ThumbnailWidthHelp {
            get {
                return ResourceManager.GetString("Admin_ThumbnailWidthHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Users.
        /// </summary>
        public static string Admin_Users {
            get {
                return ResourceManager.GetString("Admin_Users", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uservoice Import.
        /// </summary>
        public static string Admin_UservoiceImport {
            get {
                return ResourceManager.GetString("Admin_UservoiceImport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome Message.
        /// </summary>
        public static string Admin_WelcomeMessage {
            get {
                return ResourceManager.GetString("Admin_WelcomeMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your Name.
        /// </summary>
        public static string Admin_YourName {
            get {
                return ResourceManager.GetString("Admin_YourName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        public static string Common_Edit {
            get {
                return ResourceManager.GetString("Common_Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can use &lt;a href=&quot;http://daringfireball.net/projects/markdown/syntax&quot;&gt;Markdown&lt;/a&gt;!.
        /// </summary>
        public static string Common_Markdown {
            get {
                return ResourceManager.GetString("Common_Markdown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preview.
        /// </summary>
        public static string Common_Preview {
            get {
                return ResourceManager.GetString("Common_Preview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string Common_Save {
            get {
                return ResourceManager.GetString("Common_Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to unvote.
        /// </summary>
        public static string Common_UnVote {
            get {
                return ResourceManager.GetString("Common_UnVote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to vote.
        /// </summary>
        public static string Common_Vote {
            get {
                return ResourceManager.GetString("Common_Vote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Votes.
        /// </summary>
        public static string Common_Votes {
            get {
                return ResourceManager.GetString("Common_Votes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New.
        /// </summary>
        public static string Home_New {
            get {
                return ResourceManager.GetString("Home_New", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Popular.
        /// </summary>
        public static string Home_Popular {
            get {
                return ResourceManager.GetString("Home_Popular", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Top.
        /// </summary>
        public static string Home_Top {
            get {
                return ResourceManager.GetString("Home_Top", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You need to login to do that.
        /// </summary>
        public static string HomeModule_LoginRequired {
            get {
                return ResourceManager.GetString("HomeModule_LoginRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Activity Feed.
        /// </summary>
        public static string Idea_ActivityFeed {
            get {
                return ResourceManager.GetString("Idea_ActivityFeed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Comment.
        /// </summary>
        public static string Idea_AddComment {
            get {
                return ResourceManager.GetString("Idea_AddComment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Feature.
        /// </summary>
        public static string Idea_AddFeature {
            get {
                return ResourceManager.GetString("Idea_AddFeature", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        public static string Idea_Description {
            get {
                return ResourceManager.GetString("Idea_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download.
        /// </summary>
        public static string Idea_Download {
            get {
                return ResourceManager.GetString("Idea_Download", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit an idea.
        /// </summary>
        public static string Idea_Edit {
            get {
                return ResourceManager.GetString("Idea_Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Images.
        /// </summary>
        public static string Idea_Edit_AddImages {
            get {
                return ResourceManager.GetString("Idea_Edit_AddImages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please fill Title and Description.
        /// </summary>
        public static string Idea_Edit_Error {
            get {
                return ResourceManager.GetString("Idea_Edit_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Features.
        /// </summary>
        public static string Idea_Features {
            get {
                return ResourceManager.GetString("Idea_Features", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Got something to add?.
        /// </summary>
        public static string Idea_GotSomething {
            get {
                return ResourceManager.GetString("Idea_GotSomething", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to how about ....
        /// </summary>
        public static string Idea_HowAbout {
            get {
                return ResourceManager.GetString("Idea_HowAbout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Images.
        /// </summary>
        public static string Idea_Images {
            get {
                return ResourceManager.GetString("Idea_Images", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Leave a Comment.
        /// </summary>
        public static string Idea_LeaveComment {
            get {
                return ResourceManager.GetString("Idea_LeaveComment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Submit a New Idea.
        /// </summary>
        public static string Idea_New_Submit {
            get {
                return ResourceManager.GetString("Idea_New_Submit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next.
        /// </summary>
        public static string Idea_Next {
            get {
                return ResourceManager.GetString("Idea_Next", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No activity yet, add the first comment!.
        /// </summary>
        public static string Idea_NoActivity {
            get {
                return ResourceManager.GetString("Idea_NoActivity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No features suggested yet, be the first!.
        /// </summary>
        public static string Idea_NoFeatures {
            get {
                return ResourceManager.GetString("Idea_NoFeatures", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Previous.
        /// </summary>
        public static string Idea_Previous {
            get {
                return ResourceManager.GetString("Idea_Previous", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        public static string Idea_Status {
            get {
                return ResourceManager.GetString("Idea_Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Submit.
        /// </summary>
        public static string Idea_Submit {
            get {
                return ResourceManager.GetString("Idea_Submit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title.
        /// </summary>
        public static string Idea_Title {
            get {
                return ResourceManager.GetString("Idea_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tweet this Idea!.
        /// </summary>
        public static string Idea_Tweet {
            get {
                return ResourceManager.GetString("Idea_Tweet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Idea: &apos;{0}&apos; - {1}.
        /// </summary>
        public static string IdeaSecuredModule_EditIdea {
            get {
                return ResourceManager.GetString("IdeaSecuredModule_EditIdea", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Admin Panel.
        /// </summary>
        public static string Layout_AdminPanel {
            get {
                return ResourceManager.GetString("Layout_AdminPanel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        public static string Layout_Home {
            get {
                return ResourceManager.GetString("Layout_Home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log out.
        /// </summary>
        public static string Layout_LogOut {
            get {
                return ResourceManager.GetString("Layout_LogOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Idea.
        /// </summary>
        public static string Layout_NewIdea {
            get {
                return ResourceManager.GetString("Layout_NewIdea", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign In.
        /// </summary>
        public static string Layout_SignIn {
            get {
                return ResourceManager.GetString("Layout_SignIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There was a problem logging you in:.
        /// </summary>
        public static string Login_Error {
            get {
                return ResourceManager.GetString("Login_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bad response from login provider..
        /// </summary>
        public static string LoginModule_BadResponse {
            get {
                return ResourceManager.GetString("LoginModule_BadResponse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bad response from login provider - could not find login token..
        /// </summary>
        public static string LoginModule_BadResponse_NoToken {
            get {
                return ResourceManager.GetString("LoginModule_BadResponse_NoToken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bad response from login provider - could not find user..
        /// </summary>
        public static string LoginModule_BadResponse_NoUser {
            get {
                return ResourceManager.GetString("LoginModule_BadResponse_NoUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login Error.
        /// </summary>
        public static string LoginModule_LoginError {
            get {
                return ResourceManager.GetString("LoginModule_LoginError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profile.
        /// </summary>
        public static string Profile {
            get {
                return ResourceManager.GetString("Profile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email Address.
        /// </summary>
        public static string Profile_Email {
            get {
                return ResourceManager.GetString("Profile_Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Github Username.
        /// </summary>
        public static string Profile_Github {
            get {
                return ResourceManager.GetString("Profile_Github", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Name.
        /// </summary>
        public static string Profile_UserName {
            get {
                return ResourceManager.GetString("Profile_UserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username is available.
        /// </summary>
        public static string UserModule_UsernameAvailable {
            get {
                return ResourceManager.GetString("UserModule_UsernameAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username is not valid.
        /// </summary>
        public static string UserModule_UsernameNotValid {
            get {
                return ResourceManager.GetString("UserModule_UsernameNotValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username is already taken.
        /// </summary>
        public static string UserModule_UsernameTaken {
            get {
                return ResourceManager.GetString("UserModule_UsernameTaken", resourceCulture);
            }
        }
    }
}
